import { ReactNode } from "react";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logos/alt-favicon.svg" />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
